routes/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from db import db
from my_models import User

login_bp = Blueprint('login_bp', __name__)

@login_bp.route("/login")
def login():
    return render_template("login.html")

@login_bp.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")

    statement_login = db.select(User).where(User.email == email)
    result = db.session.execute(statement_login).scalar()

    if result:
   
        if result.password == password:
            session["user_id"] = result.id
            return redirect(url_for("profile_bp.profile"))
    
    flash('Please check your login details and try again.', "danger")
    return redirect(url_for('login_bp.login'))
        

routes/profile.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from db import db
from my_models import User
import os

profile_bp = Blueprint('profile_bp', __name__)

@profile_bp.route("/profile")
def profile():
    user_id = session.get("user_id")
    if not user_id:
        return redirect(url_for("login_bp.login"))
    
    usr_stmt = db.select(User).where(User.id == user_id)
    user = db.session.execute(usr_stmt).scalar()

    image_url = None
    if user and user.rental:
        model = user.rental.car.model.replace(" ", "").lower()
        year = str(user.rental.car.year)
        color = user.rental.car.color.replace(" ", "").lower()

        filename = f"{model}_{year}_{color}.png"
        filepath = os.path.join("static", "images", filename)

        if os.path.exists(filepath):
            image_url = url_for("static", filename=f"images/{filename}")
        else:
            image_url = url_for("static", filename="images/default_car.jpg")

    if user:
        return render_template("profile.html", user=user, image_url=image_url)
    else:
        return render_template("error.html")



@profile_bp.route("/profile", methods=["POST"])
def profile_post():
    user_id = session.get("user_id")
    if not user_id:
        return redirect(url_for("login_bp.login"))

    usr_stmt = db.select(User).where(User.id == user_id)
    user = db.session.execute(usr_stmt).scalar()

    if user and user.rental:
        user.rental.car.removeRental(user)

    return redirect(url_for("profile_bp.profile"))

routes/signup.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from db import db
from my_models import User

signup_bp = Blueprint('signup_bp', __name__)

@signup_bp.route("/signup")
def signup():


    return render_template("signup.html")


@signup_bp.route("/signup", methods=["POST"])
def signup_post():
    email = request.form.get("email")
    password = request.form.get("password")
    name = request.form.get("name")

    statement_login = db.select(User).where(User.email == email)
    result = db.session.execute(statement_login).scalar()
    if "@" not in email:
        flash('Email is not valid.', 'danger')
        return render_template('signup.html')
    
    has_letter = any(c.isalpha() for c in password)
    has_digit = any(c.isdigit() for c in password)
    if len(password) < 8 or not has_letter or not has_digit:
        flash('Password must be at least 8 characters and include both letters and numbers.', 'danger')
        return render_template('signup.html')
    if not result:
        
        newuser = User(username=name, email=email, password=password)
        db.session.add(newuser)
        db.session.commit()

        session["user_id"] = newuser.id
        session.permanent = True

        return redirect(url_for("profile_bp.profile"))
    flash('A user with that email already exists.', 'danger')
    return render_template('signup.html')

templates/base_navbar.html
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  crossorigin="anonymous"
/>

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/base_navbar.css') }}"
/>

<nav class="navbar navbar-expand-lg navbar-dark mb-4">
  <div class="container-fluid">
    <img
      src="/static/images/cf772c7b-629b-4f51-b1f4-eace1d959062_removalai_preview.png"
      width="10%"
      height="auto"
    />
    <a
      class="navbar-brand"
      href="/"
      style="font-family:Arial, Helvetica, sans-serif"
      font-weight="bold"
      >GreenRide</a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link {% if active_page == 'home' %}active{% endif %}"
            href="/"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if active_page == 'categories' %}active{% endif %}"
            href="/cars"
            >Browse</a
          >
        </li>

        <li class="nav-item">
          {% if session.get("user_id") %}
          <a class="nav-link" href="/profile">My Account</a>
          {% endif %}
        </li>

        <li class="nav-item">
          {% if session.get("user_id") %}
          <a class="nav-link" href="/logout">Logout</a>
          {% else %}
          <a class="nav-link" href="/login">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container mt-3">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <p class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>



{% block content %}{% endblock %}

templates/car_details.html
{% extends "base_navbar.html" %} {% block content %}

<head>
  <meta charset="UTF-8" />
  <title>{{ element.model }} Details</title>
  <style>
    body {
      font-family: Arial, sans-serif;
    }
    .car-info {
      max-width: 600px;
      margin: auto;
      border: 1px solid #ccc;
      border-radius: 8px;
      padding: 1.5rem;
      box-shadow: 0 0 8px rgba(0, 0, 0, 0.1);
    }
    .car-info h2 {
      margin-bottom: 1rem;
      color: #333;
    }
    .car-info img {
      max-width: 100%;
      height: auto;
      border-radius: 8px;
      margin-bottom: 1rem;
    }
    .car-info p {
      margin: 0.5rem 0;
    }
    .label {
      font-weight: bold;
    }
    .rental {
      display: inline-block;
      margin: 0.3rem 0.5rem;
      padding: 5px;
      border: 2px solid #f5f6f7;
      border-radius: 6px;
      color: #2f3e2e;
      text-decoration: none;
      background-color: #fafff4;
      font-weight: 500;
      transition: background-color 0.3s ease, color 0.3s ease;
    }
    .rental:hover {
      background-color: #2f3e2e;
      color: #ffffff;
    }
  </style>
</head>
<body>
  <div class="car-info" style="background-color: #f5ede4">
    <a href="{{ url_for('cars') }}" class="btn btn-secondary">← Back</a>

    <img src="{{ image_url }}" alt="{{ element.model }} image"style="width: 500px; height: 400px; object-fit: contain;" />
    <h2>{{ element.brand.name }} {{ element.model }} ({{ element.year }})</h2>
    <p><span class="label">Brand:</span> {{ element.brand.name }}</p>
    <p><span class="label">Type:</span> {{ element.carType.name }}</p>
    <p><span class="label">Color:</span> {{ element.color }}</p>
    <p><span class="label">Rate:</span> ${{ "%.2f"|format(element.rate) }}</p>
    <p><span class="label">Campus Location:</span> {{ element.campus.name }}</p>
    <p><span class="label">Milage:</span> {{ element.milage }} km</p>



  {% if element.rental == None %}
    <p style="border-radius: 5px;
              background-color: #dcedc8;
              color: #33691e;
              padding: 1rem;
              margin-top: 0.5rem;">
        <span class="label">Availability:</span> Available
    </p>
    <form action="{{ url_for('rent_car', id=element.id) }}" method="post">
      <button class="rental" type="submit">Rent</button>
    </form>
{% else %}
    <p style="border-radius: 5px;
              background-color: #edcfc8;
              color: #69211e;
              padding: 1rem;
              margin-top: 0.5rem;">
        <span class="label">Availability:</span> Unavailable
    </p>
{% endif %}

</body>

{% endblock %}

templates/cars.html
{% extends "base_navbar.html" %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/cars.css') }}">

<div class="container mb-4">

  <div class="d-flex flex-wrap align-items-center justify-content-center mb-3">
  <h5 class="mr-3 mb-2">Sort by:</h5>
  
  <a href="{{ url_for('cars', sort='rate', order='desc', search=search) }}" class="btn btn-outline-success mr-2 mb-2">Rate</a>
  <a href="{{ url_for('cars', sort='type', order='desc', search=search) }}" class="btn btn-outline-success mr-2 mb-2">Type</a>
  <a href="{{ url_for('cars', sort='location', order='desc', search=search) }}" class="btn btn-outline-success mr-2 mb-2">Location</a>


  <a href="{{ url_for('cars', sort=sort_by, order='desc' if order == 'asc' else 'asc', search=search) }}"
     class="btn btn-outline-secondary mb-2">
    {{ 'Ascending' if order == 'asc' else 'Descending' }}
  </a>
  </div>


  
  <form class="form-inline justify-content-center" method="get" action="{{ url_for('cars') }}">
    <div class="form-group mb-2 mr-2">
      <input type="text" class="form-control" name="search" placeholder="Search by model or brand" value="{{ search }}">
    </div>
    <button type="submit" class="btn btn-success mb-2">Search</button>
  </form>

</div>


<table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Model</th>
        <th scope="col">Year</th>
        <th scope="col">Brand</th>
        <th scope="col">Type</th>

        <th scope="col">Color</th>
        <th scope="col">Rate</th>
        <th scope="col">Campus</th>
        <th scope="col">Milage</th>
        <th scope="col">Available?</th>
      </tr>
    </thead>
    <tbody>
   
        {% for element in my_list %}
    
            <tr>
            <th scope="row">{{loop.index}}</th>
            <td>{{element.model}}</td>
            <td>{{element.year}}</td>
            <td>{{element.brand.name}}</td>
            <td>{{element.carType.name}}</td>

            <td>{{element.color}}</td>
            <td>${{"%.2f"|format(element.rate)}}</td>
            <td>{{element.campus.name}}</td>
            <td>{{element.milage}}</td>
            {% if element.rental %}
              <td> ❌ </td>
            {% else %}
              <td> ✅ </td>
            {% endif %}


            <td>
              <a href="{{ url_for('car_details', id=element.id) }}" class="btn btn-success btn-sm">
                View
              </a>
            </td>

            </tr>
            
        {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/error.html
{% extends "base_navbar.html" %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/errors.css') }}">

<div class="error-container">
    <h1>Error</h1>
    <p>{{ message }}</p>
    <a href="/">Return to Home</a>
</div>

{% endblock %}

templates/home.html
{% extends "base_navbar.html" %} {% block content %}

<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/home.css') }}"
/>

<section class="hero-section">
  <div class="hero-content container has-text-centered">
    <h1 class="hero-title">Drive Smart. Drive Green.</h1>
    <p >Affordable, sustainable car rentals for BCIT students and staff.</p>
    <a href="/cars"  class="button is-success is-medium">Explore Rentals</a>
  </div>
</section>

<section class="features-section container">
  <div class="columns is-multiline">
    <div class="column is-one-third feature-card">
      <div class="feature-icon">🚗</div>
      <h3>Electric & Hybrid Fleet</h3>
      <p>Choose from a range of eco-conscious vehicles for every need.</p>
      <img src="/static/images/electric-vehicle-charging.png" class="img-fluid">
    </div>
    <div class="column is-one-third feature-card">
      <div class="feature-icon">🌿</div>
      <h3>Carbon Offset Included</h3>
      <p>Your trip contributes to reforestation and clean energy projects.</p>
      <img src="/static/images/cleanenergy.jpg" class="img-fluid">
    </div>
    <div class="column is-one-third feature-card">
      <div class="feature-icon">📍</div>
      <h3>Convenient Locations</h3>
      <p>Pick up and drop off from any BCIT campus.</p>
      <img src="/static/images/bcitcampus.jpg" class="img-fluid">
    </div>
    <div class="column is-one-third feature-card">
      <h2>Ready for students, staff members and the general public</h2>
      <p>Rent your eco-friendly car today!</p>
      <a href="/signup" class="button is-success is-medium">Get Started</a>
      
    </div>
  </div>
</section>



{% endblock %}

templates/login.html
{% extends "base_navbar.html" %}


{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
      <h3 class="title text-center text-white mb-4">Login</h3>
      <div class="box">
        <form method="POST" action="/login">
          <div class="form-group">
            <input class="form-control form-control-lg" type="email" name="email" placeholder="Your Email" autofocus required>
          </div>

          <div class="form-group">
            <input class="form-control form-control-lg" type="password" name="password" placeholder="Your Password" required>
          </div>

          <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" name="remember" >
            <label class="form-check-label">Remember me</label>
          </div>

          <button class="btn btn-success btn-lg btn-block">Login</button>
        </form>

        <hr class="my-4">
        <div class="text-center">
          <h6 >Or</h6>
          <a href="{{ url_for('google_login') }}" class="btn btn-danger btn-block mb-2">
            <i class="fab fa-google mr-2"></i> Login with Google
          </a>
          <a href="{{ url_for('github_login') }}" class="btn btn-secondary btn-block">
            <i class="fab fa-github mr-2"></i> Login with GitHub
          </a>
          <p class="mb-3">Don’t have an account yet? Sign up now</p>
          <a href="{{ url_for('signup_bp.signup') }}" class="btn btn-success btn-block">
             Sign Up
          </a>

        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/profile.html
{% extends "base_navbar.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h2 class="mb-4">User Profile</h2>
            <div class="card p-4 shadow-sm">
                <p><strong>Name:</strong> {{ user.username }}</p>
                <p><strong>Email:</strong> {{ user.email }}</p>
            </div>

            {% if user.rental %}
            <div class="card mt-4 p-4 shadow-sm" style="background-color: #f5ede4;">
                <h4 class="mb-3">Current Rental</h4>
                <img src="{{ image_url }}"  class="img-fluid mb-3" alt="{{ user.rental.car.model }} image">
                <h5>{{ user.rental.car.brand.name }} {{ user.rental.car.model }} ({{ user.rental.car.year }})</h5>

                <p><strong>Brand:</strong> {{ user.rental.car.brand.name }}</p>
                <p><strong>Type:</strong> {{ user.rental.car.carType.name }}</p>
                <p><strong>Color:</strong> {{ user.rental.car.color }}</p>
                <p><strong>Rate:</strong> ${{ "%.2f"|format(user.rental.car.rate) }}</p>
                <p><strong>Campus Location:</strong> {{ user.rental.car.campus.name }}</p>
                <p><strong>Milage:</strong> {{ user.rental.car.milage }} km</p>

              

                <form action="{{ url_for('profile_bp.profile_post', user=user) }}" method="post">
                    <button class="btn btn-danger mt-2" type="submit">Return Car</button>
                </form>
            </div>
            {% else %}
                <p class="mt-4 text-muted">You have no current rentals.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/signup.html
{% extends "base_navbar.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/signup.css') }}">


<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
      <h3 class="title text-center text-white mb-4">Sign Up</h3>
      <div class="box bg-white shadow-sm">
        <form method="POST" action="/signup">
          <div class="form-group">
            <input class="form-control form-control-lg" type="email" name="email" placeholder="Email" autofocus required value="{{ request.form.get('email', '') }}">
          </div>

          <div class="form-group">
            <input class="form-control form-control-lg" type="text" name="name" placeholder="Name" required value="{{ request.form.get('name', '') }}">
          </div>

          <div class="form-group">
            <input class="form-control form-control-lg" type="password" name="password" placeholder="Password" required>
          </div>

          <button class="btn btn-info btn-lg btn-block">Sign Up</button>
        </form>

        <hr class="my-4">
        <div class="text-center">
          <p class="mb-2">Already have an account?</p>
          <a href="{{ url_for('login_bp.login') }}" class="btn btn-success btn-block">
             Login
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}